<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>lk</groupId>
  <artifactId>RideLink</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Archetype - RideLink</name>
  <url>http://maven.apache.org</url>
  <modules>
    <module>Account-Service</module>
    <module>Ride-Management-Service</module>
    <module>Driver-and-Vehicle-Service</module>
    <module>Fare-and-Payment-Service</module>
  </modules>
</project>
